import type { ManagementSection, SectionDefinition } from "./types";

export const adminSections: Record<ManagementSection, SectionDefinition> = {
  projects: { label: "Projects", singular: "project", description: "Plan, assign, and deliver your client projects with confidence.", titleLabel: "Project name", categoryLabel: "Industry", statuses: ["New", "Pending", "Active", "In Progress", "Completed", "Cancelled"], categories: ["FinTech", "Healthcare", "E-Commerce", "Enterprise", "Real Estate", "SaaS"] },
  services: { label: "Services", singular: "service", description: "Manage the capabilities your clients come to SolyNext for.", titleLabel: "Service name", categoryLabel: "Discipline", statuses: ["Published", "Draft", "Archived"], categories: ["Web", "Software", "Mobile", "Design", "Marketing", "Cloud", "Training", "Other"] },
  technologies: { label: "Technologies", singular: "technology", description: "Maintain your stack, expertise, and technology categories.", titleLabel: "Technology name", categoryLabel: "Category", statuses: ["Active", "Draft", "Archived"], categories: ["Frontend", "Backend", "Mobile", "Cloud & DevOps", "Database", "Design & Creative", "Data & AI"] },
  clients: { label: "Clients", singular: "client", description: "A clear view of client relationships and project partnerships.", titleLabel: "Company name", categoryLabel: "Industry", statuses: ["Active", "Inactive", "Prospect", "Archived"], categories: ["FinTech", "Healthcare", "E-Commerce", "Enterprise", "SaaS"] },
  reviews: { label: "Reviews", singular: "review", description: "Review client feedback before it appears on your website.", titleLabel: "Client / company", categoryLabel: "Project scope", statuses: ["Pending", "Approved", "Rejected", "Hidden", "Published", "Archived"], categories: ["Web engineering", "Custom software", "Product design", "Mobile applications"] },
  team: { label: "Team", singular: "team member", description: "Manage the people, roles, and expertise behind SolyNext.", titleLabel: "Full name", categoryLabel: "Department", statuses: ["Active", "Draft", "Archived"], categories: ["Leadership", "Engineering", "UI/UX Design", "Graphic Design", "Marketing", "Video Editing", "Project Management", "Operations"] },
  media: { label: "Media library", singular: "asset", description: "Organize brand assets, project visuals, and website imagery.", titleLabel: "Asset name", categoryLabel: "Collection", statuses: ["Ready", "Draft", "Archived"], categories: ["Brand assets", "Project visuals", "Services", "Editorial"] },
  inquiries: { label: "Contact / Inquiries", singular: "inquiry", description: "Follow up on new conversations and upcoming opportunities.", titleLabel: "Contact name", categoryLabel: "Service interest", statuses: ["New", "Contacted", "In Discussion", "Converted", "Closed"], categories: ["Web applications", "Custom software", "Mobile applications", "Product design", "Digital marketing"] },
  content: { label: "Website content", singular: "content block", description: "Prepare the copy and sections that tell your company’s story.", titleLabel: "Content title", categoryLabel: "Page", statuses: ["Published", "Draft", "Archived"], categories: ["Home", "About", "Services", "Projects", "Team", "Reviews", "Partners", "Contact", "Social links", "Insights", "Global"] },
  tasks: { label: "Tasks & workflow", singular: "task", description: "Turn project plans into clear, assigned, achievable work.", titleLabel: "Task name", categoryLabel: "Workstream", statuses: ["To Do", "In Progress", "Review", "Completed", "Blocked"], categories: ["Development", "Design", "Quality assurance", "Content", "Deployment", "Discovery"] },
  portfolio: { label: "Completed work / Portfolio", singular: "showcase", description: "Curate completed work for your public project showcase.", titleLabel: "Project title", categoryLabel: "Category", statuses: ["Published", "Draft", "Archived"], categories: ["Web application", "Mobile application", "Product design", "Custom software", "Brand identity"] },
  partners: { label: "Partners", singular: "partner", description: "Manage the relationships and brands that support SolyNext.", titleLabel: "Partner name", categoryLabel: "Partnership", statuses: ["Active", "Inactive", "Draft"], categories: ["Technology", "Delivery", "Community", "Training"] },
  roles: { label: "Roles & responsibilities", singular: "role", description: "Define team responsibilities and areas of expertise.", titleLabel: "Role name", categoryLabel: "Department", statuses: ["Active", "Draft", "Archived"], categories: ["Engineering", "Design", "Marketing", "Leadership", "Operations"] },
};

export function isManagementSection(value: string): value is ManagementSection { return Object.hasOwn(adminSections, value); }
