"use client";
import { useState } from "react";
import { Save, UploadCloud } from "lucide-react";
import type { AdminRecord, ManagementSection } from "@/lib/admin/types";
import { adminSections } from "@/lib/admin/sections";
import { PROJECT_TYPES, PROJECT_PHASES, PRIORITIES } from "@/lib/admin/selectors";
import { useAdmin } from "./AdminProvider";
import { AdminButton } from "./AdminUI";
import styles from "./admin.module.css";
export function RecordForm({section,record,categories,onSave,onCancel}:{section:ManagementSection;record?:AdminRecord;categories:string[];onSave:(record:AdminRecord)=>void;onCancel:()=>void}) {
 const {collections}=useAdmin(); const definition=adminSections[section];const [error,setError]=useState("");const [fileName,setFileName]=useState("");
 const field=(name:keyof AdminRecord,label:string,type="text")=><label key={name}>{label}<input name={name} type={type} defaultValue={String(record?.[name]??"")} maxLength={type==="text"?500:undefined} min={type==="number"?0:undefined} max={name==="progress"||name==="workload"?100:undefined} step={name==="budget"?"0.01":undefined}/></label>;
 const select=(name:keyof AdminRecord,label:string,values:string[])=><label key={name}>{label}<select name={name} defaultValue={String(record?.[name]??values[0])}>{values.map(value=><option key={value}>{value}</option>)}</select></label>;
 const relation=(name:"clientId"|"projectId"|"assignedTo",label:string,source:"clients"|"projects"|"team")=><label>{label}<select name={name} defaultValue={record?.[name]??""}><option value="">Unassigned</option>{collections[source].map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>;
 const list=(name:"technologies"|"skills",label:string)=><label>{label}<input name={name} defaultValue={record?.[name]?.join(", ")??""} placeholder="Separate items with commas" maxLength={1000}/></label>;
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const value=(key:string)=>String(form.get(key)??"").trim();if(value("startDate")&&value("deadline")&&value("deadline")<value("startDate")){setError("The deadline must be on or after the start date.");return;}const next:AdminRecord={...record,id:record?.id??crypto.randomUUID(),title:value("title"),description:value("description"),category:value("category"),status:value("status"),updatedAt:new Date().toISOString()};for(const key of ["email","phone","contactName","location","company","role","availability","clientId","projectId","assignedTo","projectType","startDate","deadline","completionDate","phase","notes","icon","url","followUpDate","followUpStatus","image"] as const){if(form.has(key))next[key]=value(key)||undefined;}for(const key of ["budget","progress","workload","rating","displayOrder"] as const){if(form.has(key))next[key]=value(key)?Number(value(key)):undefined;}for(const key of ["technologies","skills"] as const){if(form.has(key))next[key]=value(key).split(",").map(item=>item.trim()).filter(Boolean);}if(section==="projects"){next.assignedTeam=form.getAll("assignedTeam").map(String);next.priority=value("priority") as AdminRecord["priority"];if(next.status==="Completed"){next.progress=100;next.phase="Completed";}}if(section==="tasks")next.priority=value("priority") as AdminRecord["priority"];if(section==="reviews"||section==="portfolio")next.featured=form.has("featured");onSave(next);};
 return <form className={styles.form+" "+styles.recordForm} onSubmit={submit}><p className={styles.notice}>Demo workspace. Saved changes last until this workspace is reloaded.</p><label>{definition.titleLabel}<input name="title" required maxLength={180} defaultValue={record?.title??""} placeholder={"Enter "+definition.singular+" name"}/></label><div className={styles.formPair}><label>{definition.categoryLabel}<select name="category" defaultValue={record?.category??categories[0]}>{categories.map(category=><option key={category}>{category}</option>)}</select></label>{select("status","Status",definition.statuses)}</div>
 {["clients","team","inquiries"].includes(section)&&field("email","Email address","email")}
 {section==="clients"&&<><div className={styles.formPair}>{field("contactName","Contact person")}{field("phone","Phone","tel")}</div>{field("location","Location")}</>}
 {section==="projects"&&<><div className={styles.formPair}>{relation("clientId","Client","clients")}{select("projectType","Project type",PROJECT_TYPES)}</div><div className={styles.formPair}>{field("startDate","Start date","date")}{field("deadline","Deadline","date")}</div><div className={styles.formPair}>{field("budget","Budget (USD)","number")}{select("priority","Priority",[...PRIORITIES])}</div><div className={styles.formPair}>{field("progress","Completion (%)","number")}{select("phase","Current phase",PROJECT_PHASES)}</div><fieldset className={styles.assignmentField}><legend>Assigned team</legend><div>{collections.team.map(member=><label key={member.id}><input type="checkbox" name="assignedTeam" value={member.id} defaultChecked={record?.assignedTeam?.includes(member.id)}/>{member.title}</label>)}</div></fieldset>{list("technologies","Technologies")}</>}
 {section==="tasks"&&<><div className={styles.formPair}>{relation("projectId","Project","projects")}{relation("assignedTo","Assigned member","team")}</div><div className={styles.formPair}>{select("priority","Priority",[...PRIORITIES])}{field("deadline","Due date","date")}</div></>}
 {section==="team"&&<><div className={styles.formPair}>{field("role","Role")}{select("availability","Availability",["Available","Partially available","Unavailable","On leave"])}</div>{list("skills","Skills")}<div className={styles.formPair}>{field("workload","Workload (%)","number")}{field("phone","Phone","tel")}</div>{field("location","Location")}</>}
 {section==="inquiries"&&<><div className={styles.formPair}>{field("company","Company")}{relation("assignedTo","Assigned member","team")}</div><div className={styles.formPair}>{field("followUpDate","Follow-up date","date")}{select("followUpStatus","Follow-up status",["Not scheduled","Scheduled","Due","Completed"])}</div>{field("phone","Phone","tel")}</>}
 {section==="reviews"&&<><div className={styles.formPair}>{field("company","Company")}{select("rating","Rating",["5","4","3","2","1"])}</div>{relation("clientId","Client","clients")}</>}
 {section==="portfolio"&&<><div className={styles.formPair}>{relation("projectId","Completed project","projects")}{relation("clientId","Client","clients")}</div>{field("url","Project URL","url")}{field("completionDate","Completion date","date")}{list("technologies","Technologies")}</>}
 {section==="services"&&<div className={styles.formPair}>{field("icon","Icon name")}{field("displayOrder","Display order","number")}</div>}
 {section==="roles"&&list("skills","Required skills")}
 {["partners","content"].includes(section)&&field("url","Website / social URL","url")}
 {["reviews","portfolio"].includes(section)&&<label className={styles.checkLabel}><input type="checkbox" name="featured" defaultChecked={record?.featured}/>Feature on the website</label>}
 {["services","portfolio","reviews","media","partners"].includes(section)&&<label>Image / visual<select name="image" defaultValue={record?.image??""}><option value="">No image selected</option>{record?.image&&!collections.media.some(item=>item.image===record.image)&&<option value={record.image}>Current image</option>}{collections.media.map(item=><option value={item.image} key={item.id}>{item.title}</option>)}</select></label>}
 <label>{section==="reviews"?"Testimonial":section==="inquiries"?"Client message":section==="content"?"Content":"Description"}<textarea name="description" required rows={4} maxLength={5000} defaultValue={record?.description??""}/></label>
 {["projects","tasks","clients","inquiries","team"].includes(section)&&<label>Internal notes<textarea name="notes" rows={3} maxLength={5000} defaultValue={record?.notes??""}/></label>}
 {section==="media"&&<label className={styles.uploadArea}><UploadCloud size={26}/><strong>{fileName||"Choose an image"}</strong><span>File selection preview · Upload storage is not connected</span><input type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];setFileName(file?.name??"");setError(file&&file.size>10*1024*1024?"Choose an image smaller than 10 MB.":"");}}/></label>}
 {error&&<p role="alert" className={styles.formError}>{error}</p>}<div className={styles.formActions}><AdminButton type="button" variant="secondary" onClick={onCancel}>Cancel</AdminButton><AdminButton type="submit" disabled={error.includes("10 MB")}><Save size={16}/>Save preview</AdminButton></div></form>;
}
