"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Pencil, CalendarDays, Mail, Phone, MapPin, Users, FolderKanban, Star, CheckCircle2 } from "lucide-react";
import type { ManagementSection, AdminRecord } from "@/lib/admin/types";
import { adminSections } from "@/lib/admin/sections";
import { initials, projectTasks, clientProjects } from "@/lib/admin/selectors";
import { useAdmin } from "./AdminProvider";
import { AdminPageHeading, AdminButton, StatusBadge, PriorityBadge, ProgressBar, formatAdminDate } from "./AdminUI";
import { AdminDialog } from "./AdminDialog";
import { RecordForm } from "./RecordForm";
import { TaskBoard } from "./TaskBoard";
import styles from "./admin.module.css";
export function ResourceDetails({section,id}:{section:ManagementSection;id:string}) {
 const {collections,save,activity}=useAdmin();const record=collections[section].find(item=>item.id===id);const [edit,setEdit]=useState(false);const [tab,setTab]=useState("Overview");const definition=adminSections[section];
 if(!record)return <section className={styles.emptyState}><FolderKanban size={40}/><h1>Record unavailable</h1><p>This record may have been removed from the demo workspace.</p><Link href={`/admin/${section}`} className={`${styles.button} ${styles.secondary}`}>Return to {definition.label}</Link></section>;
 const projects=section==="clients"?clientProjects(collections,id):section==="team"?collections.projects.filter(project=>project.assignedTeam?.includes(id)):[];
 const tasks=section==="projects"?projectTasks(collections,id):section==="team"?collections.tasks.filter(task=>task.assignedTo===id):[];
 const client=collections.clients.find(item=>item.id===record.clientId);const team=collections.team.filter(member=>record.assignedTeam?.includes(member.id));
 const update=(changes:Partial<AdminRecord>)=>save(section,{...record,...changes,updatedAt:new Date().toISOString()});
 const projectList=<div className={styles.projectList}>{projects.map(project=><Link key={project.id} href={`/admin/projects/${project.id}`}><div><strong>{project.title}</strong><span>{project.projectType} · Due {formatAdminDate(project.deadline)}</span></div><StatusBadge status={project.status}/><ProgressBar value={project.progress}/></Link>)}{!projects.length&&<p className={styles.inlineEmpty}>No assigned projects yet.</p>}</div>;
 return <><Link href={`/admin/${section}`} className={styles.backToList}><ArrowLeft size={16}/>Back to {definition.label.toLowerCase()}</Link><AdminPageHeading title={record.title} description={section==="projects"?`${record.projectType??record.category} · ${client?.title??"Unassigned client"}`:record.role??record.category}><StatusBadge status={record.status}/>{section==="projects"&&<Link href={`/admin/portfolio?new=1&project=${encodeURIComponent(record.id)}`} className={`${styles.button} ${styles.secondary}`}>Add to public portfolio</Link>}<AdminButton onClick={()=>setEdit(true)}><Pencil size={16}/>Edit {definition.singular}</AdminButton></AdminPageHeading>
 <div className={styles.detailLayout}><aside className={styles.detailSidebar}><section className={styles.panel}><div className={styles.detailIdentity}><span className={styles.largeAvatar}>{initials(record.title)}</span><h2>{record.title}</h2><p>{record.role??record.category}</p></div><dl className={styles.summaryDetails}>{record.email&&<div><dt><Mail size={15}/>Email</dt><dd>{record.email}</dd></div>}{record.phone&&<div><dt><Phone size={15}/>Phone</dt><dd>{record.phone}</dd></div>}{record.location&&<div><dt><MapPin size={15}/>Location</dt><dd>{record.location}</dd></div>}{record.contactName&&<div><dt>Contact person</dt><dd>{record.contactName}</dd></div>}{client&&<div><dt>Client</dt><dd><Link href={`/admin/clients/${client.id}`}>{client.title}</Link></dd></div>}{record.assignedTo&&<div><dt>Assigned member</dt><dd>{collections.team.find(member=>member.id===record.assignedTo)?.title??"Unassigned"}</dd></div>}{record.projectId&&<div><dt>Project</dt><dd><Link href={`/admin/projects/${record.projectId}`}>{collections.projects.find(project=>project.id===record.projectId)?.title??"Unassigned"}</Link></dd></div>}{record.budget!==undefined&&<div><dt>Project budget</dt><dd>{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(record.budget)}</dd></div>}{record.startDate&&<div><dt>Start date</dt><dd>{formatAdminDate(record.startDate)}</dd></div>}{record.deadline&&<div><dt><CalendarDays size={15}/>Deadline</dt><dd>{formatAdminDate(record.deadline)}</dd></div>}{record.priority&&<div><dt>Priority</dt><dd><PriorityBadge priority={record.priority}/></dd></div>}{record.availability&&<div><dt>Availability</dt><dd>{record.availability}</dd></div>}{record.company&&<div><dt>Company</dt><dd>{record.company}</dd></div>}{record.followUpDate&&<div><dt>Follow-up</dt><dd>{formatAdminDate(record.followUpDate)} · {record.followUpStatus}</dd></div>}</dl>{section==="clients"&&<AdminButton variant="secondary" onClick={()=>update({status:record.status==="Active"?"Inactive":"Active"})}>{record.status==="Active"?"Deactivate client":"Activate client"}</AdminButton>}{section==="team"&&<ProgressBar value={record.workload} label="Current workload"/>}</section>{team.length>0&&<section className={styles.panel}><h2>Assigned team</h2><div className={styles.memberList}>{team.map(member=><Link href={`/admin/team/${member.id}`} key={member.id}><span className={styles.initialAvatar}>{initials(member.title)}</span><div><strong>{member.title}</strong><small>{member.role}</small></div></Link>)}</div></section>}</aside>
 <div className={styles.detailContent}>{section==="projects"&&<div className={styles.tabs} role="group" aria-label="Project details">{["Overview","Tasks","Timeline","Notes"].map(value=><button key={value} className={tab===value?styles.activeTab:""} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value}{value==="Tasks"&&<span>{tasks.length}</span>}</button>)}</div>}
 {tab==="Overview"&&<><section className={styles.panel}><div className={styles.panelHeading}><div><h2>{section==="projects"?"Project overview":section==="clients"?"Client profile":section==="team"?"Member profile":"Overview"}</h2><p>{record.category}</p></div>{section==="projects"&&<span className={styles.softLabel}>{record.phase??"Discovery"}</span>}</div><p className={styles.detailDescription}>{record.description}</p>{section==="projects"&&<><ProgressBar value={record.progress} label="Overall completion"/><div className={styles.detailMetrics}><div><strong>{tasks.filter(task=>task.status==="Completed").length}</strong><span>Completed tasks</span></div><div><strong>{tasks.filter(task=>task.status!=="Completed").length}</strong><span>Pending tasks</span></div><div><strong>{team.length}</strong><span>Assigned members</span></div></div></>}{(record.technologies?.length||record.skills?.length)?<div className={styles.tagList}>{(record.technologies??record.skills??[]).map(item=><span key={item}>{item}</span>)}</div>:null}{record.url&&<p className={styles.externalUrl}>{record.url}</p>}{section==="reviews"&&<><span className={styles.stars}>{Array.from({length:record.rating??5},(_,i)=><Star size={18} fill="currentColor" key={i}/>)}</span><div className={styles.moderationActions}>{["Approved","Rejected","Hidden"].map(status=><AdminButton key={status} variant="secondary" disabled={record.status===status} onClick={()=>update({status})}>{status=== "Approved"?"Approve":status==="Rejected"?"Reject":"Hide"}</AdminButton>)}<AdminButton variant="secondary" onClick={()=>update({featured:!record.featured})}>{record.featured?"Remove featured":"Feature review"}</AdminButton></div></>}{section==="portfolio"&&<AdminButton variant="secondary" onClick={()=>update({featured:!record.featured})}>{record.featured?"Remove featured":"Feature project"}</AdminButton>}</section>
 {["clients","team"].includes(section)&&<section className={styles.panel}><div className={styles.panelHeading}><div><h2>{section==="clients"?"Projects & history":"Assigned projects"}</h2><p>{projects.length} projects · {projects.filter(project=>project.status==="Completed").length} completed</p></div><Users size={19}/></div>{projectList}</section>}{section==="projects"&&<section className={styles.panel}><div className={styles.panelHeading}><div><h2>Delivery checklist</h2><p>Current work and the next steps</p></div><Link href="/admin/tasks">All tasks</Link></div><div className={styles.taskList}>{tasks.map(task=><Link key={task.id} href={`/admin/tasks/${task.id}`}><CheckCircle2 size={18}/><div><strong>{task.title}</strong><small>{collections.team.find(member=>member.id===task.assignedTo)?.title??"Unassigned"}</small></div><StatusBadge status={task.status}/></Link>)}{!tasks.length&&<p className={styles.inlineEmpty}>No tasks assigned to this project.</p>}</div></section>}{section==="team"&&<section className={styles.panel}><h2>Assigned tasks</h2><div className={styles.taskList}>{tasks.map(task=><Link key={task.id} href={`/admin/tasks/${task.id}`}><strong>{task.title}</strong><StatusBadge status={task.status}/></Link>)}{!tasks.length&&<p className={styles.inlineEmpty}>No tasks assigned.</p>}</div></section>}</>}
 {tab==="Tasks"&&<TaskBoard tasks={tasks}/>}{tab==="Timeline"&&<section className={styles.panel}><h2>Project timeline</h2><ol className={styles.timeline}>{record.milestones?.map(milestone=><li key={milestone.id}><i/><div><strong>{milestone.title}</strong><p>{formatAdminDate(milestone.date)}</p><StatusBadge status={milestone.status}/></div></li>)}{!record.milestones?.length&&<li><i/><div><strong>Project created</strong><p>{formatAdminDate(record.startDate??record.updatedAt)}</p></div></li>}</ol></section>}{(tab==="Notes" || (section!=="projects" && record.notes))&&<section className={styles.panel}><h2>Internal notes</h2><p className={styles.detailDescription}>{record.notes||"No notes added yet. Use Edit to add delivery context."}</p></section>}
 <section className={styles.panel}><div className={styles.panelHeading}><div><h2>Activity history</h2><p>Changes in this demo session</p></div></div><ol className={styles.timeline}>{activity.filter(item=>item.title.includes(record.title)).map(item=><li key={item.id}><i/><div><strong>{item.title}</strong><p>{item.detail}</p><small>{item.time}</small></div></li>)}</ol>{!activity.some(item=>item.title.includes(record.title))&&<p className={styles.inlineEmpty}>No recent changes to this record.</p>}</section></div></div>
 {edit&&<AdminDialog title={`Edit ${definition.singular}`} description="Update the details in this demo workspace." onClose={()=>setEdit(false)}><RecordForm section={section} record={record} categories={[...new Set([...definition.categories,record.category])]} onCancel={()=>setEdit(false)} onSave={next=>{save(section,next);setEdit(false);}}/></AdminDialog>}</>;
}
