"use client";
import { cardTone } from "@/components/ui/CardMotif";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, Search } from "lucide-react";
import { CASE_STUDIES_DATA } from "@/data/mockData";
export function PortfolioClient(){
 const [industry,setIndustry]=useState("All");
 const [query,setQuery]=useState("");
 const industries=["All",...new Set(CASE_STUDIES_DATA.map(project=>project.industry))];
 const projects=CASE_STUDIES_DATA.filter(project=>(industry==="All"||project.industry===industry)&&[project.title,project.summary,...project.technologies].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <main id="main-content" className="premium-home internal-premium"><div className="premium-container"><div className="internal-heading"><p className="eyebrow">OUR WORK</p><h1>Complex challenges.<br/>Considered solutions.</h1><p>Explore the platforms, products, and business systems in our portfolio.</p></div><div className="portfolio-controls"><div className="portfolio-filters" role="group" aria-label="Filter projects by industry">{industries.map(value=><button key={value} type="button" aria-pressed={industry===value} onClick={()=>setIndustry(value)}>{value==="All"?"All projects":value.split("&")[0].trim()}</button>)}</div><label className="portfolio-search"><Search size={17}/><input type="search" aria-label="Search projects by name or technology" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects or technologies"/></label></div><p className="portfolio-result-count" role="status">{projects.length} {projects.length===1?"project":"projects"}</p><div className="portfolio-project-grid portfolio-project-grid-compact">{projects.map(project=><article className="portfolio-project visual-card" key={project.id} data-card-tone={cardTone(project.industry)}><Link className="portfolio-image" href={`/portfolio/${project.slug}`} aria-label={`View ${project.title}`}><Image src={project.featuredImage} alt={`${project.title.split(":")[0]} case study illustration`} fill sizes="(max-width: 600px) 100vw, (max-width: 1050px) 50vw, 33vw" className="object-cover"/><span>{project.industry.split("&")[0].trim()}</span></Link><div className="portfolio-project-content"><h2><Link href={`/portfolio/${project.slug}`}>{project.title.split(":")[0]}</Link></h2>{project.client.includes("Concept project")&&<p className="project-client">Concept project</p>}<Link href={`/portfolio/${project.slug}`} className="p-text-link" aria-label={`View ${project.title} case study`}>View project <ArrowUpRight size={16}/></Link></div></article>)}</div>{projects.length===0&&<div className="portfolio-empty"><h2>No matching projects</h2><p>Try a different keyword or browse all industries.</p><button type="button" className="p-button" onClick={()=>{setQuery("");setIndustry("All");}}>Reset filters</button></div>}<div className="internal-end-cta"><div><h2>What could we build for you?</h2><p>Let&apos;s talk about your product, your users, and your next step.</p></div><Link href="/contact" className="p-button">Start a project <ArrowUpRight size={18}/></Link></div></div></main>;
}
